public enum ViewTypes
{
    EDITOR_LANUGAGES = -13,
    EDITOR_EDIT_LANGUAGE = -12,
    EDITOR_BONUSES = -11,
    EDITOR_EDIT_BONUS = -10,
    EDITOR_DIFFICULTIES = -9,
    EDITOR_EDIT_DIFFICULTY = -8,
    EDITOR_ENEMIES = -7,
    EDITOR_EDIT_ENEMY = -6,
    EDITOR_EDIT_LEVEL = -5,
    EDITOR_LEVELS = -4,
    EDITOR_EDIT_PATH = -3,
    EDITOR_PATH = -2,
    EDITOR_LANDING = -1,
	INIT = 1,
	LOAD = 2,
	GAME = 3,
	PAUSE = 4,
	SLOW = 5,
	RESULTS = 6,
    MAIN = 7,
    LEVEL_UP = 8
}

